services:

  dweebui:
    image: lllllllillllllillll/dweebui:latest  
    container_name: dweebui
    environment:
      PORT: 8000
      SECRET: My-secret
    restart: unless-stopped
    ports:
      - "8100:8000"
    volumes:
      - dweebui:/app
      # Docker socket
      - /var/run/docker.sock:/var/run/docker.sock
      # Podman socket
      #- /run/podman/podman.sock:/var/run/docker.sock

volumes:
  dweebui:

